# Generated by Django 5.2.7 on 2025-11-10 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_lesson_options_and_more'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-enrolled_at',)},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='date_enrolled',
            new_name='enrolled_at',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.lesson')),
            ],
            options={
                'ordering': ('lesson__order', 'lesson__id'),
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
