# Generated by Django 5.2.7 on 2025-11-18 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_streak_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_course', 'First Course Completed'), ('five_courses', 'Five Courses Completed'), ('ten_courses', 'Ten Courses Completed'), ('streak_7', '7 Day Streak'), ('streak_30', '30 Day Streak'), ('streak_100', '100 Day Streak'), ('perfect_progress', 'Perfect Progress'), ('early_bird', 'Early Bird')], max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-unlocked_at',),
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
